# Generated by Django 4.2.7 on 2024-01-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "distance",
                    models.FloatField(
                        choices=[
                            (3.1, "5k"),
                            (6.2, "10k"),
                            (13.1, "Half marathon"),
                            (26.2, "Marathon"),
                            (18.6, "30k"),
                            (21.7, "35k"),
                            (31.1, "50k"),
                            (50, "50 mile"),
                            (62.1, "100k"),
                            (100, "100 mile"),
                        ]
                    ),
                ),
                ("location", models.CharField(max_length=150)),
                (
                    "terrain",
                    models.CharField(
                        choices=[("trail", "Trail"), ("road", "Road")], max_length=5
                    ),
                ),
                ("elevation_gain", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
