# Generated by Django 4.2.7 on 2023-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='terrain',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
