# Generated by Django 4.2.7 on 2023-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_distance_race_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='terrain',
            field=models.CharField(default=1.0, max_length=150),
            preserve_default=False,
        ),
    ]
