# Generated by Django 4.0.3 on 2023-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_race_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
